### ISSUE TITLE
Progress Indicator beim Cache leeren wird auf manchen Websites nicht angezeigt

### ISSUE THREAD

**Issue by derUli** [derUli/ulicms#468]
Habe bisher nicht heraus gefunden was die Ursache ist. Das Problem tritt vor allem im Chrome auf.
Die Response von loading2.gif ist angeblich leer aber direkt aufrufen klappt.

Das Problem scheint nur in Webkit-Browsern aufzutreten.

**Comment by derUli** [comment]
LOADING GIF per base64 data url anzeigen
https://stackoverflow.com/questions/31797730/images-not-loading-in-chrome-when-changing-img-src-via-javascript

**Comment by derUli** [comment]
Eventuell funktioniert es auch wenn man das src Attribut vorher leert

**Comment by derUli** [comment]
```javascript
$(this).attr("src","");
$(this).removeAttr("src");
$(this).attr("src", "gfx/loading2.gif");
```

**Comment by derUli** [comment]
Noch eine LösungsIdee:
Loading gif und das Icon sind immer vorhanden und werden wechselseitig eim und ausgeblendet

**Comment by gizmore** [comment]
Warum dauert cache löschen so lange?
Was wird denn alles gelöscht?
Was für caches nutzt Du?

**Comment by derUli** [comment]
Für das Problem habe ich schon einen Fix, der in UliCMS 2017.3 enthalten sein wird.

Was die Geschwindigkeit angeht, dass hängt von mehreren Faktoren ab.
- Anzahl der Seiten
- Volltextsuche
- Installierte Indexer-Module (Der ix_files benötigt recht lange)

**Comment by derUli** [comment]
Da du eine neue Frage hast, die nur indirekt mit dem Bug zusammenhängt mache ich hier zu.
Wenn du weitere Hilfe benötigt, kannst du entweder ein neues Issue öffnen oder mir eine E-Mail schicken.

**Comment by gizmore** [comment]
Ah... also wird auch der cache direkt wieder neu erstellt?
Evtl könnte der idx_ separat behandelt werden.

PS: Wollte nur mal Fragen warum cache löschen nen indicator braucht, und grüssen.

**Comment by derUli** [comment]
nein der Cache wird nicht neu erstellt. nur der Suchindex sofern man extended_search installiert hat.
den Indicator braucht man, damit man sieht dass er was tut. Das Cache leeren erfolgt per AJAX. sonst klickt man und wundert sich das nichts passiert.
