### ISSUE TITLE
DataTables arbeiten nicht wie vorgesehen

### ISSUE THREAD

**Issue by DrCarsonBeckett** [derUli/ulicms#871]
Moin,

ich habe in "admin/scripts/util.js" den Wert "stateSave: true," überprüft. Dieser war auch so vorgegeben. Danach "stateDuration: 0," eingefügt und den Cache gelöscht (der Seite).
Die Tabellen werden immer noch nicht gespeichert bzw. nach einem wechsel der Seiten wieder zurück gesetzt.

Getestet unter Firefox Quantum (67.0.4) und wegen Sicherstellung unter IE11 (Windows 10 - 1809).

**Comment by derUli** [comment]
Ich habe dir ein Code-Snippet zugeschickt, die das Problem behebt.
Teste bitte ob das das Problem für dich behebt.

Ich werde das demnächst als Patch für 2019.3 veröffentlichen

**Comment by DrCarsonBeckett** [comment]
Klappt. :)

**Comment by derUli** [comment]
Gut, dann werde ich einen Patch für die 2019.3 erstellen

**Comment by derUli** [comment]
So, du kannst nun den Patch DataTablesSaveStateFix für die 2019.3 installieren.
